spring:
  application:
    name: bishop-prototype
  aop:
    auto: true
    proxy-target-class: true
  kafka:
    bootstrap-servers: localhost:19092
    properties:
      security.protocol: PLAINTEXT
      request.timeout.ms: 30000
      retry.backoff.ms: 1000
      delivery.timeout.ms: 45000
    producer:
      acks: all
      enable.idempotence: true
      max.in.flight.requests.per.connection: 1
      linger.ms: 5
      batch.size: 16384
  main:
    banner-mode: "off"
  server:
    port: 8081

audit:
  mode: kafka
  kafka:
    topic: android-audit-log

management:
  endpoints:
    web:
      exposure:
        include: health, metrics, prometheus
  metrics:
    tags:
      application: ${spring.application.name}

logging:
  level:
    root: info
    com.weyland.bishop: debug
    org.springframework.kafka: debug
    org.apache.kafka: debug
  pattern:
    console: "%d{yyyy-MM-dd HH:mm:ss} [%thread] %-5level %logger{50} - %msg%n"

---
spring:
  config:
    activate:
      on-profile: test
  kafka:
    bootstrap-servers: mock-server